#npg params

norm_data: 100 # same as num_frames except for synthetic human as in paper was trained for this

## Basis and MLP
weight_init_std: 0.01
key_points_no: 1500
num_candidate: 1000
shape_basis_size: 47
color_basis_size: 25
n_fully_connected: 512
initial_dim: 1  # time dimension
n_layers: 6
phi_vector_dim: 50
num_positional_encoding: 30

## weight of regularization for the points
w_reg = 100.0

## only true for the static background in the dnerf dataset
use_bgkd: False


