#dataset
render_cameras_name: projection_matrix.npz

factor: 1
novel_cameras_name: novel_projection_matrix.npz
novel_pose_available: False
novel_pose: True
novel_pose_idx: 27
novel_time: False
novel_time_idx: 16
ref_frame: 115

image_height: 512
image_width: 512
num_frames: 150 
norm_data: 150 # same as num_frames except for synthetic human

case_pose: ub4d
## train
learning_rate: 0.0005
learning_rate_alpha: 0.05
random_seed: 123
batch_size: 10
pt_cld_grp: True

# Info about Iterations, logging and saving
num_iter: 100001
report_freq: 4000
save_freq: 5000
warm_up_end: 5000
logging: 1000 

## loss weights
w_asgn: 0.1  #sinkhorn loss
w_flow: 10.0  #flow loss
w_d_plus: 100.0  # positive depth loss
w_cd: 1.0 #chamfer distance loss weight 10.0 was given in paper 
w_rgb: 1000.0  #rgb loss initial-1.0
w_d_kp: 1000000000.0 # local rigidity

## pytorch3d rasterizer
radius: 0.075
pts_per_pixel: 5

## Basis and MLP
weight_init_std: 0.01
key_points_no: 1500
num_candidate: 1000
shape_basis_size: 25
color_basis_size: 25
n_fully_connected: 512
initial_dim: 1  # time dimension
n_layers: 6
phi_vector_dim: 50
num_positional_encoding: 30

# Find K elements of the nearest neighbor in local rigidity loss
k_nn: 10




